### ISSUE TITLE
React dependencies not specified in package.json

### ISSUE THREAD

**Issue by el-guero-mero** [whelandrew/URLShortener#1]
There are two dependencies that are not specified in package.json file:

1. react
2. react-dom

Please include these in the package.json file. We should assume for the sake of review that a user would not have any pre-existing libraries installed ;)

**Comment by whelandrew** [comment]
Added and pushed. Thanks for noticing that! I forgot that my react is global on my computer.
https://github.com/whelandrew/URLShortener





From: Mateo Nares
Sent: Tuesday, October 22, 2019 9:14 AM
To: whelandrew/URLShortener
Cc: Subscribed
Subject: [whelandrew/URLShortener] React dependencies not specified inpackage.json (#1)

There are two dependencies that are not specified in package.json file:
1. react
2. react-dom
Please include these in the package.json file. We should assume for the sake of review that a user would not have any pre-existing libraries installed ;)

**Comment by el-guero-mero** [comment]
Great, thank you!
